apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-nvpn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-nvpn
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-nvpn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-nvpn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-nvpn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vslu-tenant/rhtap-demo-app/hacbs-test-project-nvpn@sha256:4bed46963c5f0a7dd6e1f135030301bef7892250f34c1febdc2cd7b70146f32f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
